### ISSUE TITLE
Supported Use Case of Service Principal Auxiliary Tenant?

### ISSUE THREAD

**Issue by bdschaap** [Azure/aad-pod-identity#1120]
Is this a supported use case for auxiliaryTenantId?

Application 1 in AAD Tenant 1
Service Principal 1 in AAD Tenant 1 associated with Application 1 has access to Azure Resource 1 (in AAD Tenant 1)
Service Principal 2 in AAD Tenant 2 associated with Application 1 has access to Azure Resource 2 (in AAD Tenant 2)
Pod that is bound to AzureIdentity can access both Azure Resource 1 and Azure Resource 2

AzureIdentity definition snippet -
```
tenantID: <AAD Tenant 1 id>
clientID: <Application 1 id>
auxiliaryTenantIDs:
- <AAD Tenant 2 id>
```

**Comment by chewong** [comment]
Yes, that should be supported. Let us know if that's not the case.

**Comment by bdschaap** [comment]
I tried the configuration described prior to posting this issue but didn't have any luck.  I'll review the configuration again to see if anything is incorrect and will post my results.

**Comment by chewong** [comment]
What's the error you are seeing? Feel free to also share your AzureIdentity and MIC & NMI logs.

More context: pod identity uses [NewMultiTenantOAuthConfig](https://github.com/Azure/go-autorest/blob/master/autorest/adal/config.go#L115-L138) to create an oauth config and [NewMultiTenantServicePrincipalToken](https://github.com/Azure/go-autorest/blob/master/autorest/adal/token.go#L1245-L1273) to get a token.

**Comment by bdschaap** [comment]
Thanks.  I'll configure it again and pull the logs.  I'm using the service principal type for AzureIdentity and only NMI.  I do not use MIC.

**Comment by bdschaap** [comment]
The nmi logs look fine and it's able to match the clientID.  I'm using Microsoft.Data.SqlClient V3 which uses Azure.Identity's ManagedIdentityCredential class.  I'm including the error message from Azure.Identity.  Perhaps there is a conflict between what is returned and what is expected.

**Logs**
```
I0803 20:26:17.814493       1 managed.go:52] clientID in request: 05ee##### REDACTED #####8236, aad-pod-identity/mypod has been matched with azure identity aad-pod-identity/podid-app1
I0803 20:26:17.814577       1 managed.go:89] matched identityType:1 adendpoint: tenantid:t1t1t1t1-t1t1-t1t1-t1t1-t1t1t1t1t1t1 auxiliaryTenantIDs:[t2t2t2t2-t2t2-t2t2-t2t2-t2t2t2t2t2t2] clientid:05ee##### REDACTED #####8236 resource:https://database.windows.net/
I0803 20:26:18.435998       1 server.go:196] status (200) took 621785493 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.200.116.205
```

**Error**
```
Unhandled exception. System.AggregateException: One or more errors occurred. (ManagedIdentityCredential authentication failed: The requested operation requires an element of type 'Object', but the target element has type 'Array'.)
 ---> Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: The requested operation requires an element of type 'Object', but the target element has type 'Array'.
 ---> System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'Array'.
   at System.Text.Json.JsonElement.EnumerateObject()
   at Azure.Identity.ManagedIdentitySource.GetTokenFromResponse(JsonElement& root)
   at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Microsoft.Data.SqlClient.ActiveDirectoryAuthenticationProvider.AcquireTokenAsync(SqlAuthenticationParameters parameters)
   --- End of inner exception stack trace ---
   at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at TestSqlClientV3.Program.Main(String[] args) in /src/TestSqlClientV3/Program.cs:line 17
```

**Comment by bdschaap** [comment]
I enabled verbose logging on the Azure.Identity library and was able to obtain the response content.  I performed 2 tests.  The first test used auxiliaryTenantIDs and the second test did not.  The first test's response was a JSON array containing two JSON objects each with access tokens.  This test returns the error mentioned earlier and explains why it said it expected an Object but received an Array .  The second test's response was just a single JSON object containing an access token.  This test succeeds.

**Test 1 Response**
[{"access_token":"..........","refresh_token":"","expires_in":"3599","expires_on":"1628042231","not_before":"1628038331","resource":"https://database.windows.net/","token_type":"Bearer",,"refresh_token":"","expires_in":"3599","expires_on":"1628042231","not_before":"1628038331","resource":"https://database.windows.net/","token_type":"Bearer"}]

**Test 2 Response**
{"access_token":"..........","refresh_token":"","expires_in":"3599","expires_on":"1628042421","not_before":"1628038521","resource":"https://database.windows.net/","token_type":"Bearer"}

Can you tell me why two access tokens are returned when using auxiliaryTenantIDs and confirm that it's supposed to do that?  I'm trying to narrow down whether the problem is with AAD Pod Identity or the Azure.Identity library.

Thanks!

**Comment by chewong** [comment]
Your test 1 response is the expected response from NMI, where the first token is the primary token from the primary tenant and the second token is the auxiliary token from the auxiliary tenant. It looks like the C# library does not have a concept of multi-tenancy and expects a non-array JSON object similar to your test 2 response. @aramase any idea how we can tackle this with C# library?

**Comment by bdschaap** [comment]
Thanks.  I believe this method contains the call to EnumerateObject that fails.

[Link to Azure.Identity ManagedIdentitySource.cs](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/identity/Azure.Identity/src/ManagedIdentitySource.cs#L93)

```
        private static AccessToken GetTokenFromResponse(in JsonElement root)
        {
            string accessToken = null;
            DateTimeOffset? expiresOn = null;

            foreach (JsonProperty prop in root.EnumerateObject())
            {
                switch (prop.Name)
                {
                    case "access_token":
                        accessToken = prop.Value.GetString();
                        break;

                    case "expires_on":
                        expiresOn = TryParseExpiresOn(prop.Value);
                        break;
                }
            }

            return accessToken != null && expiresOn.HasValue
                ? new AccessToken(accessToken, expiresOn.Value)
                : throw new AuthenticationFailedException(AuthenticationResponseInvalidFormatError);
        }
```

**Comment by aramase** [comment]
@bdschaap Thank you for opening the issue in `azure-sdk-for-net`. When requesting for a token, we get the tokens for each tenant id back in an array:

https://github.com/Azure/aad-pod-identity/blob/1cda91abd69ca1bda2c5f1f83e7c3c897f132396/pkg/auth/auth.go#L167-L172

Are you able to custom decode the result before passing it on to the Azure.Identity client?

**Comment by bdschaap** [comment]
I reviewed the Azure.Identity code but custom decoding doesn't look promising
