### ISSUE TITLE
metadata-header-required=true causes ManagedIdentityCredential authentication failed: Service request failed. (upgrade 1.8.3. -> 1.8.6)

### ISSUE THREAD

**Issue by deyanp** [Azure/aad-pod-identity#1230]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [x] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

When upgrading from 1.8.3 -> 1.8.6 (with default setting metadata-header-required=true) I started getting the below error. When I set the setting metadata-header-required=false in 1.8.6 it started working again. What could this be?

```
 ---> System.AggregateException: One or more errors occurred. (ManagedIdentityCredential authentication failed: Service request failed.
      Status: 400 (Bad Request)
      
      Content:
      
      
      Headers:
      Date: Tue, 11 Jan 2022 16:07:17 GMT
      Content-Type: application/json; charset=utf-8
      Content-Length: 89
      
      See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot)
       ---> Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
      Status: 400 (Bad Request)
      
      Content:
      
      
      Headers:
      Date: Tue, 11 Jan 2022 16:07:17 GMT
      Content-Type: application/json; charset=utf-8
      Content-Length: 89
      
      See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
       ---> Azure.RequestFailedException: Service request failed.
      Status: 400 (Bad Request)
      
      Content:
      
      
      Headers:
      Date: Tue, 11 Jan 2022 16:07:17 GMT
      Content-Type: application/json; charset=utf-8
      Content-Length: 89
      
         at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
         at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
         at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
         at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
         at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
         at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
         at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
         at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
         at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
         at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthenticateAndAuthorizeRequestAsync(HttpMessage message, TokenRequestContext context)
         at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthorizeRequestOnChallengeAsyncInternal(HttpMessage message, Boolean async)
         at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
         at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
         at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
         at Azure.Security.KeyVault.Secrets.SecretClient.GetSecretAsync(String name, String version, CancellationToken cancellationToken)
```

**Steps To Reproduce**

Upgrade from 1.8.3 to 1.8.6, or simply add setting --metadata-header-required=true ... 

**Expected behavior**

**AAD Pod Identity version**

1.8.6

**Kubernetes version**

AKS 1.21.2

**Additional context**

**Comment by deyanp** [comment]
It seems that the related error in nmi logs is:

```
E0112 10:47:19.241273       1 server.go:336] metadata header is not specified, req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.10.16.114
I0112 10:47:19.242489       1 server.go:199] status (400) took 1235271 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.10.16.114
```

**Comment by deyanp** [comment]
Ok, turned out the container/app had MSI_ENDPOINT and MSI_SECRET env vars set ... 
Then the extremely innovative code in `Azure.Identity.ManagedIdentityClient.SelectManagedIdentitySource`

```
private static ManagedIdentitySource SelectManagedIdentitySource(ManagedIdentityClientOptions options)
        {
             return AppServiceV2017ManagedIdentitySource.TryCreate(options) ??
                    CloudShellManagedIdentitySource.TryCreate(options) ??
                    AzureArcManagedIdentitySource.TryCreate(options) ??
                    ServiceFabricManagedIdentitySource.TryCreate(options) ??
					TokenExchangeManagedIdentitySource.TryCreate(options) ??
                    new ImdsManagedIdentitySource(options);
        }
```

, together with the even more genius code in Azure.Identity.AppServiceV2017ManagedIdentitySource.TryCreate

```
        public static ManagedIdentitySource TryCreate(ManagedIdentityClientOptions options)
        {
            string msiEndpoint = EnvironmentVariables.MsiEndpoint;
            string msiSecret = EnvironmentVariables.MsiSecret;

            // if BOTH the env vars MSI_ENDPOINT and MSI_SECRET are set the MsiType is AppService
            if (string.IsNullOrEmpty(msiEndpoint) || string.IsNullOrEmpty(msiSecret))
            {
                return default;
            }

            Uri endpointUri;
            try
            {
                endpointUri = new Uri(msiEndpoint);
            }
            catch (FormatException ex)
            {
                throw new AuthenticationFailedException(MsiEndpointInvalidUriError, ex);
            }

            return new AppServiceV2017ManagedIdentitySource(options.Pipeline, endpointUri, msiSecret, options.ClientId);
        }
```
and Azure.Identity.AppServiceV2017ManagedIdentitySource.CreateRequest

```
        protected override Request CreateRequest(string[] scopes)
        {
            // covert the scopes to a resource string
            string resource = ScopeUtilities.ScopesToResource(scopes);

            Request request = Pipeline.HttpPipeline.CreateRequest();

            request.Method = RequestMethod.Get;
            request.Headers.Add("secret", _secret);
            request.Uri.Reset(_endpoint);
            request.Uri.AppendQuery("api-version", AppServiceMsiApiVersion);
            request.Uri.AppendQuery("resource", resource);

            if (!string.IsNullOrEmpty(_clientId))
            {
                request.Uri.AppendQuery("clientid", _clientId);
            }

            return request;
        }
```

lead to *not* sending Metadata: true header to the IDMS, which is intercepted and rejected by the nmi pod ... Such a mess!

**Comment by aramase** [comment]
Hello 👋🏻 

Thank you for reporting the issue. The `Metadata: true` requirement already exists in IMDS. If a request is made to IMDS with no metadata header, IMDS will reject the request. xref: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=linux#frequently-asked-questions.

This was optional before in aad-pod-identity but to be secure OOTB, we have enable this check by default in pod identity too starting from release v1.8.4: https://azure.github.io/aad-pod-identity/docs/configure/feature_flags/#metadata-header-required-flag

**Comment by aramase** [comment]
If you've any feedback for the SDK, please do provide the details. 

+ @chlowell and @schaabs

**Comment by PSanetra** [comment]
@aramase should the new default value not be documented as a breaking change?
