### ISSUE TITLE
Managed Identity dropping 

### ISSUE THREAD

**Issue by slowesss** [Azure/aad-pod-identity#1312]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

We are seeing a recurring error where our application will fail due to a managed identity error. No changes will be made to any configuration, and it can be seen that the managed identity and the binding are still present on the namespace, and the correct permissions still exist in Azure. Below shows the error that we can see from the logs on the pod. 

ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(Boolean isAsync, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Storage.Blobs.BlobRestClient.Container.GetPropertiesAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, Nullable`1 timeout, String leaseId, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.ExistsInternal(Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.ExistsAsync(CancellationToken cancellationToken)
   at 

**Steps To Reproduce**

This keeps reoccurring randomly, we cannot find a way to reproduce, but deleting the pod and a new one being deployed fixes the error temporarily.  

**Expected behavior**

The application can use the managed identity to authenticate to azure 

**AAD Pod Identity version**
aadpodidentity.k8s.io/v1

**Kubernetes version**
1.21.7

**Additional context**

**Comment by slowesss** [comment]
Please can this issue be reopened as it is still an ongoing issue?
