### ISSUE TITLE
In code stats causes panic

### ISSUE THREAD

**Issue by cpuguy83** [Azure/aad-pod-identity#258]
**Describe the bug**

global stats have concurrent read/write causing corrupted data and panics.

**Steps To Reproduce**
... randomly got the panic while running a test which itself does not have any concurrency
**Expected behavior**

**AAD Pod Identity version**
master

**Kubernetes version**
N/A

**Additional context**

```
|| fatal error: concurrent map writes
|| /usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:617 +0x72 fp=0xc00053dc10 sp=0xc00053dbe0 pc=0x102f462
|| /usr/local/Cellar/go/1.12.6/libexec/src/runtime/map_faststr.go:211 +0x42a fp=0xc00053dc78 sp=0xc00053dc10 pc=0x1014f3a
|| /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/stats/stats.go:41
|| /Users/cpuguy83/go/src/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:219 +0x3403 fp=0xc00053ffd0 sp=0xc00053dc78 pc=0x1c76c43
```

**Comment by cpuguy83** [comment]
And another:

```
fatal error: concurrent map iteration and map write

goroutine 66 [running]:
runtime.throw(0x1ec253c, 0x26)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:617 +0x72 fp=0xc0003608b0 sp=0xc000360880 pc=0x102f462
runtime.mapiternext(0xc0003609a0)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/map.go:860 +0x597 fp=0xc000360938 sp=0xc0003608b0 pc=0x1010ff7
runtime.mapiterinit(0x1d56540, 0xc000317ce0, 0xc0003609a0)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/map.go:850 +0x1c9 fp=0xc000360958 sp=0xc000360938 pc=0x1010969
github.com/Azure/aad-pod-identity/pkg/mic.(*TestCrdClient).ListAssignedIDs(0xc00024d9c0, 0xc0000be770, 0x3, 0xc00050e001)
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:361 +0xcc fp=0xc000360d48 sp=0xc000360958 pc=0x1c7bd6c
github.com/Azure/aad-pod-identity/pkg/mic.TestAddDelMICClient(0xc000510000)
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:722 +0x10ed fp=0xc000360fa8 sp=0xc000360d48 pc=0x1c7f7fd
testing.tRunner(0xc000510000, 0x1f26d08)
	/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0xc0 fp=0xc000360fd0 sp=0xc000360fa8 pc=0x10efc70
runtime.goexit()
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000360fd8 sp=0xc000360fd0 pc=0x105dde1
created by testing.(*T).Run
	/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:916 +0x35a

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000510000, 0x1eb107d, 0x13, 0x1f26d08, 0x107de01)
	/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:917 +0x381
testing.runTests.func1(0xc000278400)
	/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1157 +0x78
testing.tRunner(0xc000278400, 0xc000117df8)
	/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0xc0
testing.runTests(0xc00024d720, 0x2a8dbc0, 0x5, 0x5, 0x0)
	/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1155 +0x2a9
testing.(*M).Run(0xc000307000, 0x0)
	/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1072 +0x162
main.main()
	_testmain.go:102 +0x1cb

goroutine 19 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x2a99920)
	/Users/cpuguy83/go/src/k8s.io/klog/klog.go:943 +0x8b
created by k8s.io/klog.init.0
	/Users/cpuguy83/go/src/k8s.io/klog/klog.go:403 +0x6c

goroutine 4 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x2a99860)
	/Users/cpuguy83/go/src/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/Users/cpuguy83/go/src/github.com/golang/glog/glog.go:410 +0x272

goroutine 52 [select]:
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Sync(0xc000326b40, 0xc00050e0c0)
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:122 +0x164
created by github.com/Azure/aad-pod-identity/pkg/mic.TestAddDelMICClient
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:684 +0xbff

goroutine 6 [chan send]:
github.com/Azure/aad-pod-identity/pkg/mic.TestEventRecorder.Event(...)
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:431
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Sync(0xc000326b40, 0xc00050e0c0)
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:261 +0x33a1
created by github.com/Azure/aad-pod-identity/pkg/mic.TestAddDelMICClient
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:716 +0x10ab
FAIL	github.com/Azure/aad-pod-identity/pkg/mic	0.036s
Error: Tests failed.
```

**Comment by cpuguy83** [comment]
Another:

```
E0621 15:57:32.763664   45258 mic.go:435] error returned from cloud provider
E0621 15:57:32.764837   45258 mic.go:289] error returned from cloud provider
fatal error: concurrent map writes

goroutine 24 [running]:
runtime.throw(0x1eb3040, 0x15)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:617 +0x72 fp=0xc000483c10 sp=0xc000483be0 pc=0x102f462
runtime.mapassign_faststr(0x1d53960, 0xc00003c4e0, 0x1ea79fd, 0x6, 0xc00003c510)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/map_faststr.go:211 +0x42a fp=0xc000483c78 sp=0xc000483c10 pc=0x1014f3a
github.com/Azure/aad-pod-identity/pkg/stats.Put(...)
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/stats/stats.go:41
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Sync(0xc000124000, 0xc000160420)
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:158 +0x363a fp=0xc000485fd0 sp=0xc000483c78 pc=0x1c76e9a
runtime.goexit()
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000485fd8 sp=0xc000485fd0 pc=0x105dde1
created by github.com/Azure/aad-pod-identity/pkg/mic.TestAddDelMICClient
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:716 +0x10ab

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0004e0100, 0x1eaf5ad, 0x11, 0x1f26d30, 0x107de01)
	/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:917 +0x381
testing.runTests.func1(0xc00029a400)
	/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1157 +0x78
testing.tRunner(0xc00029a400, 0xc00016fdf8)
	/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0xc0
testing.runTests(0xc00026f780, 0x2a8dbc0, 0x5, 0x5, 0x0)
	/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1155 +0x2a9
testing.(*M).Run(0xc00031f000, 0x0)
	/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1072 +0x162
main.main()
	_testmain.go:102 +0x1cb

goroutine 4 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x2a99920)
	/Users/cpuguy83/go/src/k8s.io/klog/klog.go:943 +0x8b
created by k8s.io/klog.init.0
	/Users/cpuguy83/go/src/k8s.io/klog/klog.go:403 +0x6c

goroutine 34 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x2a99860)
	/Users/cpuguy83/go/src/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/Users/cpuguy83/go/src/github.com/golang/glog/glog.go:410 +0x272

goroutine 10 [select]:
github.com/Azure/aad-pod-identity/pkg/mic.TestEventRecorder.WaitForEvents(0xc0001dd4d0, 0xc000048230, 0x3, 0xc000160660)
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:415 +0xbb
github.com/Azure/aad-pod-identity/pkg/mic.TestMicAddDelVMSS(0xc0004e0100)
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:785 +0xc26
testing.tRunner(0xc0004e0100, 0x1f26d30)
	/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:916 +0x35a

goroutine 9 [runnable]:
runtime.Caller(0x3, 0x3801460, 0xc0000c2005, 0xc000042140, 0x38096c8, 0x105f601)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/extern.go:183 +0xfb
github.com/golang/glog.(*loggingT).header(0x2a99860, 0xc000000000, 0x0, 0x0, 0xc1a255ca, 0x118b12805d374680, 0x107d97a)
	/Users/cpuguy83/go/src/github.com/golang/glog/glog.go:536 +0x33
github.com/golang/glog.(*loggingT).printf(0x2a99860, 0xc000000000, 0x1ebe732, 0x22, 0xc00016e340, 0x3, 0x3)
	/Users/cpuguy83/go/src/github.com/golang/glog/glog.go:650 +0x46
github.com/golang/glog.Infof(...)
	/Users/cpuguy83/go/src/github.com/golang/glog/glog.go:1073
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Sync(0xc000124000, 0xc000160420)
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:311 +0x1e6e
created by github.com/Azure/aad-pod-identity/pkg/mic.TestAddDelMICClient
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:684 +0xbff

goroutine 11 [runnable]:
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Sync(0xc000124720, 0xc000160660)
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:116 +0x36d2
created by github.com/Azure/aad-pod-identity/pkg/mic.TestMicAddDelVMSS
	/Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:780 +0xba9
FAIL	github.com/Azure/aad-pod-identity/pkg/mic	0.040s
Error: Tests failed.
```

**Comment by cpuguy83** [comment]
Here's a run with `go test -race`

<details>

```
==================
WARNING: DATA RACE
Read at 0x00c0000c2360 by goroutine 11:
  runtime.mapiterinit()
      /usr/local/Cellar/go/1.12.6/libexec/src/runtime/map.go:804 +0x0
  github.com/Azure/aad-pod-identity/pkg/mic.(*TestCrdClient).ListAssignedIDs()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:360 +0x11d
  github.com/Azure/aad-pod-identity/pkg/mic.TestSimpleMICClient()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:576 +0x153f
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163

Previous write at 0x00c0000c2360 by goroutine 12:
  runtime.mapdelete_faststr()
      /usr/local/Cellar/go/1.12.6/libexec/src/runtime/map_faststr.go:297 +0x0
  github.com/Azure/aad-pod-identity/pkg/mic.(*TestCrdClient).RemoveAssignedIdentity()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:299 +0x95
  github.com/Azure/aad-pod-identity/pkg/mic.(*Client).removeAssignedIDsWithDeps()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:427 +0x78
  github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Sync()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:231 +0x350c

Goroutine 11 (running) created at:
  testing.(*T).Run()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:916 +0x65a
  testing.runTests.func1()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1157 +0xa8
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163
  testing.runTests()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:46 +0x222

Goroutine 12 (running) created at:
  github.com/Azure/aad-pod-identity/pkg/mic.TestSimpleMICClient()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:539 +0x1204
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163
==================
==================
WARNING: DATA RACE
Write at 0x00c0000da070 by goroutine 11:
  github.com/Azure/aad-pod-identity/pkg/mic.TestSimpleMICClient()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:39 +0x170e
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163

Previous read at 0x00c0000da070 by goroutine 12:
  github.com/Azure/aad-pod-identity/pkg/mic.(*TestVMClient).CreateOrUpdate()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:57 +0xaf
  github.com/Azure/aad-pod-identity/pkg/cloudprovider.(*Client).getIdentityResource.func2()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/cloudprovider/cloudprovider.go:206 +0x18b
  github.com/Azure/aad-pod-identity/pkg/cloudprovider.(*Client).RemoveUserMSI()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/cloudprovider/cloudprovider.go:132 +0x27d
  github.com/Azure/aad-pod-identity/pkg/mic.(*TestCloudClient).RemoveUserMSI()
      <autogenerated>:1 +0x7f
  github.com/Azure/aad-pod-identity/pkg/mic.(*Client).removeAssignedIDsWithDeps()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:441 +0x2c6
  github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Sync()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:231 +0x350c

Goroutine 11 (running) created at:
  testing.(*T).Run()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:916 +0x65a
  testing.runTests.func1()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1157 +0xa8
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163
  testing.runTests()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:46 +0x222

Goroutine 12 (running) created at:
  github.com/Azure/aad-pod-identity/pkg/mic.TestSimpleMICClient()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:539 +0x1204
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163
==================
==================
WARNING: DATA RACE
Write at 0x00c0000da0e0 by goroutine 11:
  github.com/Azure/aad-pod-identity/pkg/mic.TestSimpleMICClient()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:251 +0x19a1
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163

Previous read at 0x00c0000da0e0 by goroutine 12:
  github.com/Azure/aad-pod-identity/pkg/mic.(*TestPodClient).GetPods()
      <autogenerated>:1 +0x53
  github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Sync()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:129 +0x25b

Goroutine 11 (running) created at:
  testing.(*T).Run()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:916 +0x65a
  testing.runTests.func1()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1157 +0xa8
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163
  testing.runTests()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:46 +0x222

Goroutine 12 (running) created at:
  github.com/Azure/aad-pod-identity/pkg/mic.TestSimpleMICClient()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:539 +0x1204
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163
==================
--- FAIL: TestSimpleMICClient (10.00s)
    testing.go:809: race detected during execution of test
==================
WARNING: DATA RACE
Write at 0x00000341c670 by goroutine 15:
  github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Sync()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/stats/stats.go:36 +0x157

Previous write at 0x00000341c670 by goroutine 12:
  github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Sync()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/stats/stats.go:36 +0x157

Goroutine 15 (running) created at:
  github.com/Azure/aad-pod-identity/pkg/mic.TestAddDelMICClient()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:672 +0x18de
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163

Goroutine 12 (running) created at:
  github.com/Azure/aad-pod-identity/pkg/mic.TestSimpleMICClient()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:539 +0x1204
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163
==================
==================
WARNING: DATA RACE
Write at 0x00c0003a42d0 by goroutine 16:
  runtime.mapassign_faststr()
      /usr/local/Cellar/go/1.12.6/libexec/src/runtime/map_faststr.go:202 +0x0
  github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Sync()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/stats/stats.go:41 +0x3f6c

Previous read at 0x00c0003a42d0 by goroutine 15:
  runtime.mapaccess1_faststr()
      /usr/local/Cellar/go/1.12.6/libexec/src/runtime/map_faststr.go:12 +0x0
  github.com/Azure/aad-pod-identity/pkg/stats.PrintSync()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/stats/stats.go:59 +0x4d6
  github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Sync()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:293 +0x2325

Goroutine 16 (running) created at:
  github.com/Azure/aad-pod-identity/pkg/mic.TestAddDelMICClient()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:702 +0x2148
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163

Goroutine 15 (running) created at:
  github.com/Azure/aad-pod-identity/pkg/mic.TestAddDelMICClient()
      /Users/cpuguy83/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:672 +0x18de
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163
==================
--- FAIL: TestAddDelMICClient (0.00s)
    testing.go:809: race detected during execution of test
```

</details>
