### ISSUE TITLE
Nil pointer exception on CI run

### ISSUE THREAD

**Issue by cpuguy83** [Azure/aad-pod-identity#296]
**Describe the bug**

On #295 CI caused a NPE:

```
E0718 18:41:07.839633   11476 mic.go:683] Applying binding testbinding node test-node for pod test-pod-default-test-id resulted in error error returned from cloud provider
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc27050]

goroutine 10 [running]:
github.com/Azure/aad-pod-identity/pkg/cloudprovider.(*vmIdentityInfo).GetUserIdentityList(0xc00032e040, 0x13a5740, 0xc00032e040, 0xc00032e038)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/aad-pod-identity/pkg/cloudprovider/vm.go:120 +0x10
github.com/Azure/aad-pod-identity/pkg/cloudprovider.(*Client).GetUserMSIs(0xc0003b7600, 0xc0002c5b80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/aad-pod-identity/pkg/cloudprovider/cloudprovider.go:166 +0x114
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).getUserMSIListForNode(0xc0003e0af0, 0xc0002c5b80, 0x0, 0x0, 0xc0004f0380, 0x1, 0x1)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:560 +0x3e
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).updateUserMSI(0xc0003e0af0, 0x0, 0x0, 0x0, 0x124bf01, 0x9, 0x0, 0x0, 0x0, 0xc0004f0360, ...)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:667 +0x1210
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).updateNodeAndDeps(0xc0003e0af0, 0x0, 0x0, 0x0, 0xc0000b3b60, 0xc0004ee180)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:631 +0x14a
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Sync(0xc0003e0af0, 0xc000096c00)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:238 +0x959
github.com/Azure/aad-pod-identity/pkg/mic.(*TestMICClient).testRunSync.func1(0xc00000e688, 0xc000096c00, 0xc000096ba0)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:629 +0x38
created by github.com/Azure/aad-pod-identity/pkg/mic.(*TestMICClient).testRunSync
	/home/vsts/work/1/s/gopath/src/github.com/Azure/aad-pod-identity/pkg/mic/mic_test.go:628 +0xb7
FAIL	github.com/Azure/aad-pod-identity/pkg/mic	0.016s
```

**Comment by kkmsft** [comment]
Several locking improvements have been added in the tests. Closing this for now. But will re-open if we find any in future.
