### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kwaazaar** [Azure/aad-pod-identity#510]
**Describe the bug**
Seeing a panic logged. Not clear if this is mic or something else.

The command I execute: kubectl logs -n default --since=5m -l component=mic
Output:
~~~
I0218 14:20:59.319983       1 mic.go:888] Updating msis on node aks-agentpool-71662594-12 failed, but identity berichten-jobs-stuuringeplandeberichten-cronjob-binding has successfully been removed from node
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11b4201]

goroutine 73 [running]:
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).updateUserMSI(0xc0000c75e0, 0xc000720150, 0xc0007cd360, 0x18, 0xc000102a00, 0xb, 0x10, 0xc00071e300, 0x8, 0x8, ...)
        /go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:882 +0x1541
created by github.com/Azure/aad-pod-identity/pkg/mic.(*Client).updateNodeAndDeps
        /go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:780 +0x1bc
I0218 14:19:23.605881       1 mic.go:888] Updating msis on node aks-agentpool-71662594-1 failed, but identity kenuwklant-jobs-statusuitstaandeamlscreeningophalen-binding has successfully been removed from node
I0218 14:19:23.860791       1 mic.go:888] Updating msis on node aks-agentpool-71662594-12 failed, but identity berichten-jobs-stuuringeplandeberichten-cronjob-binding has successfully been removed from node
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11b4201]

goroutine 148 [running]:
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).updateUserMSI(0xc0000c72c0, 0xc00068ee40, 0xc0007db140, 0x18, 0xc0001d7d00, 0xb, 0x10, 0xc0013a0000, 0x8, 0x8, ...)
        /go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:882 +0x1541
created by github.com/Azure/aad-pod-identity/pkg/mic.(*Client).updateNodeAndDeps
        /go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:780 +0x1bc
~~~

**Steps To Reproduce**
kubectl logs -n default --since=5m -l component=mic

**Expected behavior**
No panics.

**AAD Pod Identity version**
Latest

**Kubernetes version**
1.14.8

**Additional context**
-

**Comment by kwaazaar** [comment]
One of the configured AzureIdentities had invalid configuration (ResourceId pointed to the wrong resourcegroup). After I fixed that, this error disappeared and _another_ AzureAssignedIdentity suddenly started working (the pod successfully obtained an accesstoken).

**Comment by aramase** [comment]
@kwaazaar The identity assignment is done in a batch and a cloud operation PUT is made with the required identities in the batch to be assigned/removed. So if there is an error in one identity the entire cloud PUT operation fails.

**Comment by kwaazaar** [comment]
It's not just a failing PUT operation. The mic pods themselve crash. This is the end of the log, just before a restart:
~~~
E0303 10:56:02.201039       1 mic.go:884] Binding testrobert-binding removal from node aks-agentpool-71662594-8 for pod appauthtest-cronjob-1583232480-wrqpm resulted in error compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="FailedIdentityOperation" Message="Identity operation for resource '/subscriptions/7b520150-0df3-4adb-83b7-5646c7c62fef/resourceGroups/MC_aks-ot-rg_aahnl-kubernetes-ot_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-71662594-8' failed with error 'Failed to perform resource identity operation. Status: 'BadRequest'. Response: '{\"error\":{\"code\":\"BadRequest\",\"message\":\"Resource '/subscriptions/7b520150-0df3-4adb-83b7-5646c7c62fef/resourcegroups/MC_aks-ot-rg_aahnl-kubernetes-ot_westeurope/providers/Microsoft.ManagedIdentity/userAssignedIdentities/msi-test-berichten-jobs-stuuringeplandeberichten-cronjob' was not found.\"}}'.'."
I0303 10:56:02.202695       1 mic.go:888] Updating msis on node aks-agentpool-71662594-8 failed, but identity berichten-jobs-stuuringeplandeberichten-cronjob-binding has successfully been removed from node
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11b4201]

goroutine 1844 [running]:
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).updateUserMSI(0xc000356780, 0xc001a7c990, 0xc0006fc920, 0x18, 0xc000624200, 0x8, 0x8, 0xc0019e6040, 0x3, 0x4, ...)
        /go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:882 +0x1541
created by github.com/Azure/aad-pod-identity/pkg/mic.(*Client).updateNodeAndDeps
        /go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:780 +0x1bc
~~~

**Comment by kkmsft** [comment]
@kwaazaar - We tried repro with two scenarios:
- ResourceID pointing to wrong resource group (non existing).
- ResourceID pointing to wrong resource group (existing but different).

We were not able to repro the panic. 

- Could you please let us know if there were anything else in the environment we could replicate to repro the issue ? 
- When you say the latest - did you use 1.5.5 or image created with the code from the master branch ?

**Comment by kwaazaar** [comment]
I use 1.5.5 by using the yaml.

I initially created the identities in the node resource group (MC_...) and later deleted them and recreated them **with the same name** in a different resource group. The AKS service principle has the **proper permissions in both resource groups**.

Maybe this is related to issue #521 .
