### ISSUE TITLE
NMI daemonset keeps rebooting - Iptables version erro

### ISSUE THREAD

**Issue by Grisson** [Azure/aad-pod-identity#877]
Hi here,

I try to set up aad pod identity in my cluster. Somehow, the pods keep rebooting itself due to iptable version checking error.
Following are the detail error message.

```
I1123 06:40:32.295239       1 main.go:84] starting nmi process. Version: v1.7.0. Build date: 2020-11-13-00:18.                                    │ I1123 06:40:32.398777       1 crd.go:447] CRD lite informers started                                                                                                                                           │ I1123 06:40:32.499057       1 main.go:111] running NMI in namespaced mode: false                                                                                                                               │ I1123 06:40:32.499099       1 nmi.go:53] initializing in standard mode                                                                                                                                         │ I1123 06:40:32.499108       1 probes.go:41] initialized health probe on port 8085                                                                                                                              │ I1123 06:40:32.499114       1 probes.go:44] started health probe                                                                                                                                               │ I1123 06:40:32.499204       1 metrics.go:341] registered views for metric                                                                                                                                      │ I1123 06:40:32.499276       1 prometheus_exporter.go:21] starting Prometheus exporter                                                                                                                          │ I1123 06:40:32.499296       1 metrics.go:347] registered and exported metrics on port 9090                                                                                                                     │ I1123 06:40:32.499308       1 server.go:98] listening on port 2579                                                                                                                                             │ F1123 06:40:37.508704       1 server.go:109] error checking iptables version: exit status 2                                                                                                                    │ goroutine 61 [running]:                                                                                                                                                                                        │ k8s.io/klog/v2.stacks(0xc00000e001, 0xc00016a000, 0x5c, 0xc4)                                                                                                                                                  │     /go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:996 +0xb9                                                                                                                                                        │ k8s.io/klog/v2.(*loggingT).output(0x2188a40, 0xc000000003, 0x0, 0x0, 0xc000600ee0, 0x20ebffe, 0x9, 0x6d, 0x0) 
```

aad-pod-identity version:  1.7.0
kubernetes: 1.17.13
node OS image: AKSUbuntu-1604-2020.10.28

Could you please let me know how to solve this issue?

**Comment by aramase** [comment]
@Grisson How did you setup pod identity on your cluster? 

```
error checking iptables version: exit status 2  
```

means NMI doesn't have enough permissions to check the iptables version.  For `v1.7.0` we switched to setting the default user to non root for docker build and set `runAsUser: 0` as part of the daemonset (Ref: https://github.com/Azure/aad-pod-identity/blob/v1.7.0/deploy/infra/deployment-rbac.yaml#L149-L150). If that's missing then it'll result in the above error.

**Comment by Grisson** [comment]
Thanks @aramase. Adding "runAsUser: 0" solve the problem. I may delete it when fixing the “AAD Pod Identity is not supported for Kubenet” issue. 

Thank you so much for your help.
